package com.register.farmerregistration.local.managers;

import com.register.farmerregistration.local.annotation.EntityAnnotation;
import com.register.farmerregistration.local.entities.AgroInputCategory;
import com.register.farmerregistration.local.repository.AgroInputCategoryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
@EntityAnnotation(entityClass = AgroInputCategory.class)
public class AgroInputCategoryManager extends BaseManager<AgroInputCategory, Long> {

	private AgroInputCategoryRepository agroInputCategoryRepository;

	@Autowired
	public AgroInputCategoryManager(AgroInputCategoryRepository agroInputCategoryRepository) {
		this.agroInputCategoryRepository = agroInputCategoryRepository;
	}

}
