package com.register.farmerregistration.local.managers;

import com.register.farmerregistration.local.annotation.EntityAnnotation;
import com.register.farmerregistration.local.entities.FarmData;
import com.register.farmerregistration.local.repository.AgroInputDisbursedRepository;
import com.register.farmerregistration.local.repository.FarmDataRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Generated by Spring Data Generator on 22/06/2019
 */
@Component
@EntityAnnotation(entityClass = FarmData.class)

public class DisbursementManager extends BaseManager<FarmData, Integer, FarmDataRepository> {


    private AgroInputDisbursedRepository disbursementRepository;

    @Autowired
    public DisbursementManager(AgroInputDisbursedRepository disbursedRepository) {
        this.disbursementRepository = disbursedRepository;
    }

}
