package com.register.farmerregistration.local.managers;

import com.register.farmerregistration.local.annotation.EntityAnnotation;
import com.register.farmerregistration.local.entities.FarmData;
import com.register.farmerregistration.local.repository.FarmDataRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Generated by Spring Data Generator on 22/06/2019
 */
@Component
@EntityAnnotation(entityClass = FarmData.class)

public class FarmDataManager extends BaseManager<FarmData, Integer, FarmDataRepository> {


    private FarmDataRepository farmDataRepository;

    @Autowired
    public FarmDataManager(FarmDataRepository farmDataRepository) {
        this.farmDataRepository = farmDataRepository;
    }


    public List<FarmData> findAllByUserType(String useType) {
        return farmDataRepository.findByUser_UserType(useType);
    }
}
