package com.register.farmerregistration.local.managers;

import com.register.farmerregistration.local.entities.FarmData;
import com.register.farmerregistration.local.entities.LocalGovt;
import com.register.farmerregistration.local.repository.FarmDataRepository;
import com.register.farmerregistration.local.repository.LocalGovtRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 23/06/2019
*/
@Component
public class LocalGovtManager extends BaseManager<LocalGovt, Integer, LocalGovtRepository> {

	private LocalGovtRepository localGovtRepository;

	@Autowired
	public LocalGovtManager(LocalGovtRepository localGovtRepository) {
		this.localGovtRepository = localGovtRepository;
	}

}
