package com.register.farmerregistration.local.managers;

import com.register.farmerregistration.local.annotation.EntityAnnotation;
import com.register.farmerregistration.local.entities.User;
import com.register.farmerregistration.local.repository.UserRepository;
import com.register.farmerregistration.util.lambdaworks.Hash;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Generated by Spring Data Generator on 14/05/2019
 */
@Slf4j
@EntityAnnotation(entityClass = User.class)
@Component("localUserManager")
public class UserManager extends BaseManager<User, Integer, UserRepository> {

    private UserRepository userRepository;

    @Autowired
    public UserManager(UserRepository userRepository) {
        this.userRepository = userRepository;
    }


    public List<User> findAllByUserType(String userType) {
        return userRepository.findAllByUserType(userType);
    }

    public boolean login(String username, String password) {
        System.out.println("User manager-findby: " + username);
        try {
            System.out.println("find by: " + username);
            User allUser = userRepository.findByEmail(username);
            if (allUser != null) {
                System.out.println(username + " found");
                String dbPassword = allUser.getPassword();
                return Hash.bcryptcheck(password, dbPassword);
            } else{
                System.out.println(username + " not found");
            }

            return false;
        } catch (Exception ex) {
            log.error("Exception caught", ex);
            return false;
        }
    }


}
