package com.register.farmerregistration.local.managers;

import com.register.farmerregistration.local.annotation.EntityAnnotation;
import com.register.farmerregistration.local.entities.User;
import com.register.farmerregistration.local.repository.UserRepository;
import com.register.farmerregistration.util.lambdaworks.Hash;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Generated by Spring Data Generator on 14/05/2019
 */
@Slf4j
@EntityAnnotation(entityClass = User.class)
@Component("localUserManager")
public class UserManager extends BaseManager<User, Long, UserRepository> {

    private UserRepository userRepository;

    @Autowired
    public UserManager(UserRepository userRepository) {
        this.userRepository = userRepository;
    }


    public boolean login(String username, String password) {
        try {
            User allUser = userRepository.findByEmail(username);
            if (allUser != null) {
                String dbPassword = allUser.getPassword();
                return Hash.bcryptcheck(password, dbPassword);
            }

            return false;
        } catch (Exception ex) {
            log.error("Exception caught", ex);
            return false;
        }
    }



}
