package com.register.farmerregistration.local.repository;

import com.register.farmerregistration.local.entities.Contact;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Repository
public interface ContactRepository extends BaseRepository<Contact, Long>  {

}
