package com.register.farmerregistration.local.repository;

import com.register.farmerregistration.local.entities.LocalGovt;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Generated by Spring Data Generator on 23/06/2019
 */
@Repository
public interface LocalGovtRepository extends BaseRepository<LocalGovt, Integer> {
    List<LocalGovt> findByStateId(Integer stateID);
}
