package com.register.farmerregistration.local.repository;

import com.register.farmerregistration.local.entities.State;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * Generated by Spring Data Generator on 23/06/2019
 */
@Repository
public interface StateRepository extends BaseRepository<State, Integer> {

}
